src/Entity/Formateur.php
<?php

namespace App\Entity;

use App\Repository\FormateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FormateurRepository::class)]
class Formateur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nomFormateur = null;

    #[ORM\Column(length: 50)]
    private ?string $prenomFormateur = null;

    #[ORM\Column(length: 20)]
    private ?string $sexe = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateNaissance = null;

    #[ORM\Column(length: 100)]
    private ?string $email = null;

    #[ORM\Column(length: 50)]
    private ?string $telephone = null;

    #[ORM\OneToMany(mappedBy: 'formateur', targetEntity: Session::class, orphanRemoval: true)]
    private Collection $sessions;

    public function __construct()
    {
        $this->sessions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomFormateur(): ?string
    {
        return $this->nomFormateur;
    }

    public function setNomFormateur(string $nomFormateur): static
    {
        $this->nomFormateur = $nomFormateur;

        return $this;
    }

    public function getPrenomFormateur(): ?string
    {
        return $this->prenomFormateur;
    }

    public function setPrenomFormateur(string $prenomFormateur): static
    {
        $this->prenomFormateur = $prenomFormateur;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): static
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->dateNaissance;
    }

    public function setDateNaissance(\DateTimeInterface $dateNaissance): static
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    /**
     * @return Collection<int, Session>
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): static
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions->add($session);
            $session->setFormateur($this);
        }

        return $this;
    }

    public function removeSession(Session $session): static
    {
        if ($this->sessions->removeElement($session)) {
            // set the owning side to null (unless already changed)
            if ($session->getFormateur() === $this) {
                $session->setFormateur(null);
            }
        }

        return $this;
    }

    public function __toString() {
        return $this->prenomFormateur. " " . $this->nomFormateur;
    }

    public function getAge() : ?string {
        $now = new \DateTime();
        $interval = $this->dateNaissance->diff($now);
        return $interval->format("%Y");
    }
}

src/Form/FormateurType.php
<?php

namespace App\Form;

use App\Entity\Formateur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class FormateurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        // On ajoute les champs du formulaire
        $builder
            ->add('nomFormateur', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ]
            ])

            ->add('prenomFormateur', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ]
                ])

            ->add('sexe', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ]
            ])

            ->add('dateNaissance', DateType::class, [
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'form_control'
                ]
            ])

            ->add('email', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ]
            ])

            ->add('telephone', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ]
            ])

            ->add('valider', SubmitType::class, [
                'attr' => [
                    'class' => 'btn-submit'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Formateur::class,
        ]);
    }
}

src/Controller/FormateurController.php
<?php

namespace App\Controller;

use App\Entity\Formateur;
use App\Form\FormateurType;
use App\Repository\FormateurRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class FormateurController extends AbstractController
{
    // Fonction permettant d'afficher tous les formateurs
    #[Route('/formateur', name: 'app_formateur')] // URL
    public function index(FormateurRepository $formateurRepository): Response
    {
        if($this->getUser()) {

        // Récupère tous les formateurs dans l'ordre alphabétique des noms de formateur
        $formateurs = $formateurRepository->findBy([], ['nomFormateur' => 'ASC']);

        // Renvoie la vue 'formateur/index.html.twig' avec les formateurs
        return $this->render('formateur/index.html.twig', [
            'formateurs' => $formateurs,
        ]);
        }
        return $this->redirectToRoute('app_login');
    }

    #[Route('/formateur/new', name: 'new_formateur')]
    #[Route('/formateur/{id}/edit', name: 'edit_formateur')]
    public function new_edit(Formateur $formateur = null, Request $request = null, EntityManagerInterface $entityMananger) : Response {
        if($this->getUser()) {
            // Si il existe
        if(!$formateur) {
            // On instancie le manager
            $formateur = new Formateur();
        }

        // On récupère le form de l'entity FormateurType
        $form = $this->createForm(FormateurType::class, $formateur);

        $form->handleRequest($request);

        // Si il est soumis et valide
        if($form->isSubmitted() && $form->isValid()) {
            $formateur = $form->getData();

            $entityMananger->persist($formateur); // prepare PDO
            $entityMananger->flush(); // execute PDO

            return $this->redirectToRoute('app_formateur');
        }
        // Renvoie la vue 'formateur/new.html.twig' avec le form
        return $this->render('formateur/new.html.twig', [
            'formAddFormateur' => $form
        ]);
    }
    return $this->redirectToRoute('app_login');
    }

    // Fonction permettant de supprimer un formateur
    #[Route('/formateur/{id}/delete', name: 'delete_formateur')] // URL
    public function delete(Formateur $formateur, EntityManagerInterface $entityMananger) {
        if($this->getUser()) {
        
        $entityMananger->remove($formateur); // prepare PDO
        $entityMananger->flush(); // execute PDO

        // Redirection vers la page formateur
        return $this->redirectToRoute('app_formateur');
        }

    return $this->redirectToRoute('app_login');
    }

    // Fonction permettant d'afficher un formateur
    #[Route('/formateur/{id}', name: 'show_formateur')] // URL
    public function showFormateur(Formateur $formateur) : Response {
        if ($this->getUser()) {
        
        // Renvoie la vue 'formateur/show.html.twig' avec le formateur
        return $this->render('formateur/show.html.twig', [
            'formateur' => $formateur
        ]);
    }
    return $this->redirectToRoute('app_login');
    }
}

templates/formateur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des formateurs{% endblock %}

{% block body %}
<h1>Liste des formateurs</h1>
{% for formateur in formateurs %}
<div style="padding: 10px;">
    <a href="{{ path('show_formateur', {'id' : formateur.id }) }}">{{ formateur }}</a>

    <a style="color: brown;" href="{{ path('delete_formateur', {'id' : formateur.id}) }}">Supprimer</a>
    <br>
</div>
{% endfor %}
<div style="margin: 10px; border:1px solid #007bff; width:fit-content; border-radius:5px; padding:10px;">
    <a href="{{ path('new_formateur') }}">Ajouter un formateur</a>
</div>
{% endblock %}

templates/formateur/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un employé{% endblock %}

{% block body %}


{# Formulaire d'ajout/edit formateur #}
{{ form_start(formAddFormateur) }}

{{ form_row(formAddFormateur.nomFormateur) }}
{{ form_row(formAddFormateur.prenomFormateur) }}
{{ form_row(formAddFormateur.sexe) }}
{{ form_row(formAddFormateur.dateNaissance) }}
{{ form_row(formAddFormateur.email) }}
{{ form_row(formAddFormateur.telephone) }}
{{ form_row(formAddFormateur.valider) }}

{{ form_end(formAddFormateur) }}

{% endblock %}

templates/formateur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fiche de {{ formateur }}{% endblock %}

{% block body %}

<h1>Fiche du formateur</h1>

<a href="{{ path('edit_formateur', {'id' : formateur.id}) }}" >Editer</a> <br>

<strong>{{ formateur }}</strong>
<ul style="list-style: none;">
    <li>Sexe : {{ formateur.sexe }} </li>
    <li>Date de naissance : {{ formateur.dateNaissance|date("d-m-Y") }} ({{ formateur.age }} ans)</li>
    <li>Ville : STRASBOURG</li>
    <li>Courriel : {{ formateur.email }}</li>
    <li>Téléphone : {{ formateur.telephone }}</li>
</ul>

<h2>Sessions</h2>
{# Table avec les sessions du formateur et les dates de début et de fin #}
<table border="1" class="table table-striped">
    <thead>
        <tr>
            <th>Formation</th>
            <th>Session</th>
            <th>Date de début</th>
            <th>Date de fin</th>
            <th>Inscrits</th>
        </tr>
    </thead>
    <tbody>
        {% for session in formateur.sessions %}
        <tr>
            <td>{{ session.formation.nomFormation }}</td>
            <td><a href="{{ path('show_session', {'id' : session.id}) }}">{{ session }}</a></td>
            <td>{{ session.dateDebut|date("d-m-Y") }}</td>
            <td>{{ session.dateFin|date("d-m-Y") }}</td>
            {# Le nombre de places qui reste selon le nombre de stagiaires inscrits #}
            <td>{{ session.stagiaires|length }}/{{ session.nbPlaces }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}